services:
  - type: web
    name: flora-genetics-backend
    runtime: docker
    env: docker
    plan: free
    region: ohio  # Choose a region closest to your users
    dockerfilePath: Dockerfile
    port: 8080
    envVars:
      - key: RUST_LOG
        value: info